backend:
  name: git-gateway
  branch: main
  repo: southbay82/v15-sailing

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: URL, name: url, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Category, name: category, widget: select, options: [Techniques, Maintenance, History] }
  - name: parts
    label: Parts
    folder: content/parts
    create: true
    fields:
      - { label: Vendor, name: vendor, widget: string }
      - { label: URL, name: url, widget: string }
      - { label: Description, name: description, widget: text }
  - name: regattas
    label: Regattas
    folder: content/regattas
    create: true
    fields:
      - { label: Event Name, name: name, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Location, name: location, widget: string }
      - { label: Registration URL, name: url, widget: string }
